name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
jobs:
  unit-test:
    strategy:
      matrix:
        go: [ '1.12', '1.13', '1.18', '1.20', '1.21' ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: unit test
        run: go test -v -coverprofile=coverage.out ./...
      - name: codecov
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
          fail_ci_if_error: true
          files: coverage.out